In [56]:
import os
import click
import logging
from dotenv import find_dotenv, load_dotenv

import pandas as pd
import numpy as np
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Dropout, Flatten, Dense
from keras import applications
from keras.utils import np_utils
from keras import optimizers

from pathlib import Path
from PIL import Image

In [11]:
bottleneck_features_path = '../data/interim/'
output_filepath = '../models/fer2013-01/'
top_model_weights_path = output_filepath + '/bottleneck_weights_model.h5'
top_model_path = output_filepath + '/bottleneck_model.h5'
nb_train_samples = 1852
nb_validation_samples = 468
nb_classes = 7
epochs = 2
batch_size = 16

In [12]:
train_data = np.load(open(bottleneck_features_path + 'bottleneck_features_train.npy', 'rb'))

In [14]:
train_data_len = len(train_data)
train_labels_not_encoded = np.array(
    [0] * (nb_train_samples // nb_classes) +
    [1] * (nb_train_samples // nb_classes) +
    [2] * (nb_train_samples // nb_classes) +
    [3] * (nb_train_samples // nb_classes) +
    [4] * (nb_train_samples // nb_classes) +
    [5] * (nb_train_samples // nb_classes) +
    [6] * (nb_train_samples // nb_classes))
train_labels = np_utils.to_categorical(train_labels_not_encoded)
train_labels = train_labels[0:train_data_len]

In [16]:
train_labels.shape

(1840, 7)

In [17]:
train_data.shape

(1840, 1, 1, 512)

In [58]:
opt = optimizers.SGD(lr=0.01, momentum=0.0, decay=0.0, nesterov=False)

## Initial images Grayscale to RGB

In [21]:
img_path = '../data/processed/fer2013/all/train/angry/0000.jpg'
# img_path = '../data/processed/fer2013/all/train/angry/0000.jpg'

In [35]:
from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img

datagen = ImageDataGenerator(
        rotation_range=10,
        width_shift_range=0.2,
        height_shift_range=0.2,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True,
        fill_mode='nearest')

In [37]:
img = load_img(img_path)  # this is a PIL image
x = img_to_array(img)  # this is a Numpy array with shape (3, 150, 150)
x = x.reshape((1,) + x.shape)  # this is a Numpy array with shape (1, 3, 150, 150)

# the .flow() command below generates batches of randomly transformed images
# and saves the results to the `preview/` directory
i = 0
for batch in datagen.flow(x, batch_size=1,
                          save_to_dir='../data/interim/preview', save_prefix='pic', save_format='jpeg'):
    i += 1
    if i > 9:
        break  # otherwise the generator would loop indefinitely

In [45]:
img1 = x[0]

In [48]:
img1[:,:,0]

array([[  74.,   77.,   78., ...,   53.,   44.,   40.],
       [  60.,   60.,   60., ...,   55.,   51.,   46.],
       [  48.,   53.,   59., ...,   50.,   51.,   46.],
       ..., 
       [  85.,   69.,   48., ...,   82.,   58.,   39.],
       [  81.,   83.,   78., ...,   97.,   71.,   43.],
       [  76.,   77.,   82., ...,  111.,  105.,   84.]], dtype=float32)

In [49]:
img1[:,:,1]

array([[  74.,   77.,   78., ...,   53.,   44.,   40.],
       [  60.,   60.,   60., ...,   55.,   51.,   46.],
       [  48.,   53.,   59., ...,   50.,   51.,   46.],
       ..., 
       [  85.,   69.,   48., ...,   82.,   58.,   39.],
       [  81.,   83.,   78., ...,   97.,   71.,   43.],
       [  76.,   77.,   82., ...,  111.,  105.,   84.]], dtype=float32)

In [50]:
img1[:,:,2]

array([[  74.,   77.,   78., ...,   53.,   44.,   40.],
       [  60.,   60.,   60., ...,   55.,   51.,   46.],
       [  48.,   53.,   59., ...,   50.,   51.,   46.],
       ..., 
       [  85.,   69.,   48., ...,   82.,   58.,   39.],
       [  81.,   83.,   78., ...,   97.,   71.,   43.],
       [  76.,   77.,   82., ...,  111.,  105.,   84.]], dtype=float32)